[settings]
  ID = "cncf-contributor-strategy"

[build]
  base = "/"
  publish = "website/public/"
  command = "git submodule update --init --recursive && hugo -s website --debug --verbose"

[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"

[context.branch-deploy]
  command = "git submodule update --init --recursive && hugo -s website --debug --verbose -b $DEPLOY_PRIME_URL/"
  
[context.deploy-preview]
  command = "git submodule update --init --recursive && hugo -s website --debug --verbose -b $DEPLOY_PRIME_URL/"
