name: Sync Staging
on:
  push:
    branches:
      - master

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Sync Staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: staging
          github_token: ${{ github.token }}
